Metrics/LineLength:
  Max: 103

Documentation:
  Enabled: false

AllCops:
  Include:
    - Rakefile
    - config.ru
  Exclude:
    - 'config/**/*'
    - 'script/**/*'
    - 'test'
    - 'spec/spec_helper.rb'
    - 'db/schema.rb'
    - 'db/migrate/*'
    - 'bin/*'
  